"""fix_telnyx_column_ghost

Revision ID: c7d7ba081e00
Revises: 30bfdf910b5b
Create Date: 2026-02-06 21:26:57.003579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7d7ba081e00'
down_revision: Union[str, Sequence[str], None] = '30bfdf910b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('max_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('agent_configs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('agent_configs', sa.Column('inactivity_message', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('environment_telnyx_fixed', sa.String(), nullable=True))
    # op.alter_column('agent_configs', 'interruption_phrases',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.JSON(),
    #            existing_nullable=True)
    op.drop_column('agent_configs', 'allowed_api_keys')
    op.drop_column('agent_configs', 'custom_headers')
    op.drop_column('agent_configs', 'sub_account_id')
    op.drop_column('agent_configs', 'environment_telnyx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('environment_telnyx', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agent_configs', sa.Column('sub_account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agent_configs', sa.Column('custom_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_configs', sa.Column('allowed_api_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('agent_configs', 'interruption_phrases',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('agent_configs', 'environment_telnyx_fixed')
    op.drop_column('agent_configs', 'inactivity_message')
    op.drop_column('agent_configs', 'max_retries')
    op.drop_column('agent_configs', 'max_duration_seconds')
    # ### end Alembic commands ###
